/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PokemonesVista;

import DAOpokemones.DAOpokemones;
import MenuPrincipal.MenuPrincipal;
import javax.swing.JOptionPane;
import pokemones.PokemonesController;

/**
 *
 * @author dafer
 */
public class EditarPokemon extends javax.swing.JFrame {

    private static EditarPokemon editarPokemon;
    /**
     * Creates new form editarPokemon
     */
    private EditarPokemon() {
        initComponents();
    }
    
    public static EditarPokemon getInstance(){
        if(editarPokemon == null)
            editarPokemon=new EditarPokemon();        
        return editarPokemon;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sexodepokemon = new javax.swing.ButtonGroup();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        TexFieCodPok = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        TexFieNomPok = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        cH_Electrico = new javax.swing.JCheckBox();
        cH_Fuego = new javax.swing.JCheckBox();
        cH_Agua = new javax.swing.JCheckBox();
        cH_Planta = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        rD_Ma = new javax.swing.JRadioButton();
        rD_He = new javax.swing.JRadioButton();
        cH_Variocolor = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        sliEst = new javax.swing.JSlider();
        spiEst = new javax.swing.JSpinner();
        jPanel7 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 48)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Editar Pokemon");
        getContentPane().add(jLabel5, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.GridLayout(0, 1));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Codigo pokedex"));
        jPanel6.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        TexFieCodPok.setEditable(false);
        TexFieCodPok.setText("Codigo");
        TexFieCodPok.setToolTipText("");
        TexFieCodPok.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TexFieCodPokKeyTyped(evt);
            }
        });
        jPanel6.add(TexFieCodPok);

        jPanel1.add(jPanel6);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre del pokemon"));
        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        TexFieNomPok.setText("Nombre");
        TexFieNomPok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TexFieNomPokMouseClicked(evt);
            }
        });
        jPanel5.add(TexFieNomPok);

        jPanel1.add(jPanel5);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo"));
        jPanel2.setLayout(new java.awt.GridLayout(0, 2));

        cH_Electrico.setText("Electrico");
        cH_Electrico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cH_ElectricoActionPerformed(evt);
            }
        });
        jPanel2.add(cH_Electrico);

        cH_Fuego.setText("Fuego");
        jPanel2.add(cH_Fuego);

        cH_Agua.setText("Agua");
        jPanel2.add(cH_Agua);

        cH_Planta.setText("Planta");
        jPanel2.add(cH_Planta);

        jPanel1.add(jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Sexo"));
        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        sexodepokemon.add(rD_Ma);
        rD_Ma.setText("Macho");
        jPanel3.add(rD_Ma);

        sexodepokemon.add(rD_He);
        rD_He.setText("Hembra");
        jPanel3.add(rD_He);

        jPanel1.add(jPanel3);

        cH_Variocolor.setText("Vario Color");
        jPanel1.add(cH_Variocolor);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Estadisticas"));
        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        sliEst.setMinorTickSpacing(10);
        sliEst.setPaintLabels(true);
        sliEst.setPaintTicks(true);
        sliEst.setSnapToTicks(true);
        sliEst.setToolTipText("0");
        sliEst.setValue(0);
        sliEst.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliEstStateChanged(evt);
            }
        });
        jPanel4.add(sliEst);

        spiEst.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), Float.valueOf(0.0f), Float.valueOf(100.0f), Float.valueOf(1.0f)));
        spiEst.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spiEstStateChanged(evt);
            }
        });
        jPanel4.add(spiEst);

        jPanel1.add(jPanel4);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel7.setLayout(new java.awt.GridLayout(1, 0));

        jButton1.setText("Actualizar pokemon");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton1);

        jButton2.setText("Regresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton2);

        getContentPane().add(jPanel7, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void porDefecto(){
        TexFieCodPok.setText("Codigo");
        TexFieNomPok.setText("Nombre");
        cH_Agua.setSelected(false);
        cH_Electrico.setSelected(false);
        cH_Fuego.setSelected(false);
        cH_Planta.setSelected(false);
        rD_Ma.setSelected(false);
        rD_He.setSelected(false);
        sexodepokemon.clearSelection();
        cH_Variocolor.setSelected(false); 
        spiEst.setValue(0);
    }
    
    public void datosPorActualizar(String[] pokemon){
        TexFieCodPok.setText(pokemon[0]);
        TexFieNomPok.setText(pokemon[1]);
        String[] tipos=pokemon[2].split(" ");
        for(int i=0;i<tipos.length;i++){
            switch(tipos[i]){
                case "Agua": cH_Agua.setSelected(true); break;
                case "Electrico": cH_Electrico.setSelected(true); break;
                case "Fuego": cH_Fuego.setSelected(true); break;
                case "Planta": cH_Planta.setSelected(true); break;
            }
        }
        sexodepokemon.clearSelection();
        if(pokemon[3].equals("Macho")){
            rD_Ma.setSelected(true);
        }else{
            rD_He.setSelected(true);
        }
        if(pokemon[4].equals("Si")){
            cH_Variocolor.setSelected(true); 
        }else{
            cH_Variocolor.setSelected(false);
        }
        spiEst.setValue(Integer.parseInt(pokemon[5]));
        
        
        
    }
    private void cH_ElectricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cH_ElectricoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cH_ElectricoActionPerformed

    private void TexFieNomPokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TexFieNomPokMouseClicked
        // TODO add your handling code here:
        TexFieNomPok.setText("");
    }//GEN-LAST:event_TexFieNomPokMouseClicked

    private void TexFieCodPokKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TexFieCodPokKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar())) evt.consume();
        
    }//GEN-LAST:event_TexFieCodPokKeyTyped

    private void sliEstStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliEstStateChanged
        // TODO add your handling code here:
        spiEst.setValue(sliEst.getValue());
    }//GEN-LAST:event_sliEstStateChanged

    private void spiEstStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spiEstStateChanged
        // TODO add your handling code here:  
        sliEst.setValue((int) Float.parseFloat(spiEst.getValue()+""));
       
    }//GEN-LAST:event_spiEstStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        MostrarPokemon mosPokInterfaz = MostrarPokemon.getInstance();
        mosPokInterfaz.setVisible(true);
        this.dispose();        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DAOpokemones pokCont = PokemonesController.getInstance();
        String codPok=TexFieCodPok.getText();
        String nomPok=TexFieNomPok.getText();
        String tipPok="";
        if(cH_Agua.isSelected())
            tipPok+="Agua ";
        if(cH_Electrico.isSelected())
            tipPok+="Electrico ";
        if(cH_Fuego.isSelected())
            tipPok+="Fuego ";
        if(cH_Planta.isSelected())
            tipPok+="Planta ";
        String sexPok="";
        if(rD_Ma.isSelected()){
            sexPok="Macho";
        }else{
            sexPok="Hembra";
        }
        String varPok="";
        if(cH_Variocolor.isSelected()){
            varPok="Si";
        }else{
            varPok="No";
        }
        String estPok=spiEst.getValue().toString();
        String[] pokemon={codPok,nomPok,tipPok,sexPok,varPok,estPok};
        if(pokCont.ActualizarPokemon(pokemon))
            JOptionPane.showMessageDialog(this, "ACtualización Exitosa");
        
    }//GEN-LAST:event_jButton1ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TexFieCodPok;
    private javax.swing.JTextField TexFieNomPok;
    private javax.swing.JCheckBox cH_Agua;
    private javax.swing.JCheckBox cH_Electrico;
    private javax.swing.JCheckBox cH_Fuego;
    private javax.swing.JCheckBox cH_Planta;
    private javax.swing.JCheckBox cH_Variocolor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton rD_He;
    private javax.swing.JRadioButton rD_Ma;
    private javax.swing.ButtonGroup sexodepokemon;
    private javax.swing.JSlider sliEst;
    private javax.swing.JSpinner spiEst;
    // End of variables declaration//GEN-END:variables
}
